db.url=jdbc:mysql://localhost:3306/pqciot_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
db.username=pqc_user
db.password=
db.pool.maxSize=20
db.pool.minIdle=2
db.pool.connectionTimeoutMs=20000
db.pool.idleTimeoutMs=120000
db.pool.maxLifetimeMs=300000
db.pool.leakDetectionMs=15000

mode=PQC
input.mode=SIMULATED
device.count=10
device.interval.ms=2000
dataset.path=src/main/resources/UNSW-NB15/UNSW_NB15_training-set.csv

